DROP TABLE "C##TRIPIFY"."COMMENTS"; CASCADE CONSTRAINTS;
CREATE TABLE "C##TRIPIFY"."COMMENTS" (
  "COMMENT_ID" NUMBER VISIBLE DEFAULT "C##TRIPIFY"."COMMENT_SEQ"."NEXTVAL" NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "POST_ID" NUMBER VISIBLE NOT NULL,
  "COMMENTING_DATE" DATE VISIBLE DEFAULT CURRENT_DATE,
  "TEXT" VARCHAR2(1000 BYTE) VISIBLE,
  "UPVOTE_COUNT" NUMBER VISIBLE DEFAULT 0
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of COMMENTS
-- ----------------------------
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('4', '1', '1', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), 'This is a great post!', '10');
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('5', '1', '1', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), 'Another Comment done', '10');
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('3', '2', '2', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), 'This is a great post!', '10');
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('6', '1', '1', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), 'Yet Another comment done!', '10');
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('7', '1', '8', TO_DATE('2023-08-03 22:39:19', 'SYYYY-MM-DD HH24:MI:SS'), 'cool post', '0');
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('8', '1', '1', TO_DATE('2023-08-04 02:32:27', 'SYYYY-MM-DD HH24:MI:SS'), 'wow, Canada is cool', '0');
INSERT INTO "C##TRIPIFY"."COMMENTS" VALUES ('9', '1', '20', TO_DATE('2023-08-04 02:33:06', 'SYYYY-MM-DD HH24:MI:SS'), 'wow, Canada is cool', '0');

-- ----------------------------
-- Table structure for CONNECTS
-- ----------------------------
DROP TABLE "C##TRIPIFY"."CONNECTS"; CASCADE CONSTRAINTS;
CREATE TABLE "C##TRIPIFY"."CONNECTS" (
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "GROUP_ID" NUMBER VISIBLE NOT NULL,
  "CONNECTED_AT" DATE VISIBLE DEFAULT CURRENT_DATE
)